// Writes src/components/icons.gen.ts: the Phosphor icons the app uses, as
// static SVG markup in only the weights it draws. Each Phosphor component
// carries all six weights, which cost about a kilobyte gzipped per icon; this
// keeps two or three. Add a name to NAMES and run `node scripts/icons.mjs`.
// Phosphor Icons are MIT licensed (https://phosphoricons.com).
import { writeFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";

const NAMES = [
  "ArrowsDownUp", "CaretDown", "CaretRight", "ChartLineUp", "ClipboardText", "DotsThreeVertical", "Football", "GearSix",
  "Lightning", "MagnifyingGlass", "Moon", "Plus", "Question", "SealCheck", "ShieldCheck", "ShieldStar", "SlidersHorizontal",
  "SquaresFour", "Star", "Strategy", "Sun", "Table", "Trash", "TrendDown", "Trophy", "UserFocus", "Warning", "X",
];
const WEIGHTS = ["regular", "fill", "bold"];

const out = {};
for (const n of NAMES) {
  // By path: the package's export map does not expose its per-icon defs.
  const mod = await import(new URL(`../node_modules/@phosphor-icons/react/dist/defs/${n}.es.js`, import.meta.url).href);
  const defs = Object.values(mod).find((v) => v instanceof Map);
  out[n] = Object.fromEntries(WEIGHTS.map((w) => [w, renderToStaticMarkup(defs.get(w))]));
}
const body = Object.entries(out).map(([n, w]) => `  ${n}: ${JSON.stringify(w)},`).join("\n");
writeFileSync(new URL("../src/components/icons.gen.ts", import.meta.url),
  `// Generated by scripts/icons.mjs from Phosphor Icons (MIT). Do not edit by hand.\nexport type IconWeight = ${WEIGHTS.map((w) => JSON.stringify(w)).join(" | ")};\nexport const PATHS: Record<string, Record<IconWeight, string>> = {\n${body}\n};\n`);
console.log(`wrote ${NAMES.length} icons`);
